spring:
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: Iv1.c86f2cfa22ce3447
            client-secret: c4608319c20ac434840285535b2c37bd5b0b60e7
  data:
    cassandra:
      keyspace-name: main
      username: obTfAIQmNFETJxjFfqnNBzJj
      password: OS9+MwB3,t6biI0sMZk_BeTojHJpDJm3p12Xjyd9Q0rKsQt_NLHwx+oBjTIIW4q3uyziCLr4.1rCg5PcEi,OF9zP1Fkt3fYT9D_5XdeXIF+A-Z4Fw7l6AgoceHWfTA+a
      schema-action: create_if_not_exists
      request:
        timeout: 10s
      connection:
        connect-timeout: 10s
        init-query-timeout: 10s

#datadump.location:
#  author: C:\learning\java\youtube\betterreads-dataloader\src\main\resources\test-authors.txt
#  works: C:\learning\java\youtube\betterreads-dataloader\src\main\resources\test-works.txt

datastax.astra:
  secure-connect-bundle: secure-connect-betterreads.zip

astra.db:
  id: 977c6060-8e3a-4395-b778-6828c2f9a131-1
  region: us-east1
  keyspace: main
  application.token: AstraCS:obTfAIQmNFETJxjFfqnNBzJj:870c29a5fc0b7bd8e586c210cba409b87c2596a19959f045d701484457191646